##
##
## .Author: Mickael P. Golovin.
## .Copyright: 1997-2001 by Archivarius Team, free for non commercial use.
##
##
!include	"_default.mak"
##
!ifndef		_MAKEFILE_INC
		_MAKEFILE_INC=1
##=================================== begin ===================================
##==================================== end ====================================
!endif
