USES
 'W:\shared\models\NewSchool\MDProcess.root.script'
;

USES
 'W:\shared\models\NewSchool\Templates\MDALike.tpl.script'
;

: Gen

//help
WordAliasByRef X_MDAClass :: UIDS_LIST 46E1540F00AB ;
WordAliasByRef X_MDALibrary :: UIDS_LIST 46E155F80242 ;
//help

: OUT IN %S
 //%S |N .
 %SN .
 //%S |S .
 %SS .
 %S %ST %ST |N .
 %S %ST %ST %ST |N .
 %S %ST %ST %ST %ST |N .
 //%S |U .
 %SU .
;

: X IN %S
 %S OUT
 //%S %P OUT
 %S%P OUT
 //%S %P %P OUT
 %S%P%P OUT
 //%S %P %P %P OUT
 %S%P%P%P OUT
 //%S %P %P %P %P OUT
 %S%P%P%P%P OUT
 //%S %P %P %P %P %P OUT
 %S%P%P%P%P%P OUT
;

@ <<MDAClass>> %R IT X
@ <<MDALibrary>> %R IT X
@ X_MDAClass %R IT X
@ X_MDALibrary %R IT X

@ <<MDAClass>> %G IT X
@ <<MDALibrary>> %G IT X

'' .

ARRAY A
@ X_MDAClass %R >>> A
//[[ :: X_MDAClass %R ; ]] >>> A
@ X ITERATE A

'' .

@ X_MDALibrary %R >>> A
//[[ :: X_MDALibrary %R ; ]] >>> A
@ X ITERATE A

//ARRAY A
//[[ <<MDAClass>> %G ]] >>> A

;

Gen