unit l3;

{ Библиотека "L3 (Low Level Library)" }
{ Автор: Люлин А.В. © }
{ Модуль: l3 - }
{ Начат: 12.04.98 16:27 }
{ $Id: L3.PAS,v 1.4 2005/04/16 11:41:27 lulin Exp $ }

// $Log: L3.PAS,v $
// Revision 1.4  2005/04/16 11:41:27  lulin
// - слил с веткой. Теперь из ветки можно вытягивать ТОЛЬКО Everest.
//
// Revision 1.3.46.1  2005/04/13 10:20:04  lulin
// - cleanup.
//
// Revision 1.3  2000/12/15 15:13:40  law
// - вставлены директивы Log.
//

{$Include l3Define.inc }

interface

implementation

end.

