USES
 Controls.script
 F1ControlsDefinition.script
;

USES
 SysUtils.script
;

ARRAY g_RemindersWasOuted

: "Нажать на медаль и проверить наличие баллона" STRING IN aReminder

 : Действия1
  OnTest

  aReminder byname:control:push pop:control:Visible 
   [[ 'Медаль ' aReminder ' не появилась' ]] strings:Cat 
    ASSERTS
  // - убеждаемся что медаль таки появилась
 aReminder byname:control:push pop:control:Click
 // - нажимаем на медаль
  OnTest
 ;
 "Выполнить {(@ Действия1)} и восстановить фокус"

 : Действия2
  aReminder byname:control:push pop:reminder:IsBaloonVisible 
   [[ 'Баллон медали ' aReminder ' не появился' ]] strings:Cat 
    ASSERTS
 aReminder byname:control:push pop:reminder:FindEditor pop:control:SetFocus 'Не удалось поставить фокус в редактор баллона' ASSERTS
   VAR l_File
   [[ script:FileName sysutils:ExtractFileName '' sysutils:ChangeFileExt
   '_' aReminder ]] strings:Cat >>> l_File
   
   VAR l_Count
   g_RemindersWasOuted aReminder array:StringCount >>> l_Count
   
   l_Count >0 IF
    [[ l_File '_' l_Count IntToStr ]] strings:Cat >>> l_File
    // - тут есть недоделка - третий эталон перетрёт второй, нужны массивы записей или доступ к массиву по индексу
    // - теперь вроде бы нет - за счёт l_Count
   ENDIF
   
   aReminder >>>[] g_RemindersWasOuted
   
   "Убедиться, что фокус в редакторе"
   
   l_File '.evd' sysutils:ChangeFileExt >>> l_File
   l_File focused:control:push pop:editor:TextToFile
   l_File '%' tests:CheckEtalon

  OnTest
 ;

 "Выполнить {(@ Действия2)} и восстановить фокус"
;

: "Проверяем, что баллон у медали не видим" STRING IN aReminder
 aReminder byname:control:push pop:reminder:IsBaloonVisible ! 
  [[ 'Баллон медали ' aReminder ' видим, а должен быть невидим' ]] strings:Cat 
   ASSERTS
;

: "Проверяем, что баллон у красной медали МВ не видим"
 "Проверяем, что баллон у медали {("Красная медаль МВ")} не видим"
;

: "Нажать на красную медаль МВ и проверить наличие баллона"
 "Нажать на медаль {("Красная медаль МВ")} и проверить наличие баллона"
;

: "Нажать на зелёную медаль МВ и проверить наличие баллона"
 "Нажать на медаль {("Зелёная медаль МВ")} и проверить наличие баллона"
;

: "Нажать на зелёную медаль МВ в списке и проверить наличие баллона"
 "Нажать на медаль {("Зелёная медаль МВ в списке")} и проверить наличие баллона"
;

: "Нажать на жёлтую медаль с восклицательным знаком и проверить наличие баллона"
 "Нажать на медаль {("Жёлтая медаль с восклицательным знаком")} и проверить наличие баллона"
; 

: "Нажать на жёлтую медаль с часами и проверить наличие баллона"
 "Нажать на медаль {("Жёлтая медаль с часами")} и проверить наличие баллона"
; 

: "Нажать на красную медаль с крестом и проверить наличие баллона"
 "Нажать на медаль {("Красная медаль с крестом")} и проверить наличие баллона"
; 

: "Нажать на красную медаль с вопросительным знаком и проверить наличие баллона"
 "Нажать на медаль {("Красная медаль с вопросительным знаком")} и проверить наличие баллона"
;

: "Нажать на синюю медаль МГО и проверить наличие баллона"
 "Нажать на медаль {("Синяя медаль МГО")} и проверить наличие баллона"
;

: "Нажать на синюю медаль о наличии консультаций и проверить наличие баллона"
 "Нажать на медаль {("Синяя медаль о наличии консультаций")} и проверить наличие баллона"
;

:  "Нажать на синюю медаль, сообщающую, что документ изменился и проверить наличие баллона"
 "Нажать на медаль {("Синяя медаль документов на контроле")} и проверить наличие баллона"
;

:  "Нажать на жёлтую медаль, сообщающую, что к списку применены фильтры и проверить наличие баллона"
 "Нажать на медаль {("Медаль отфильтрованного списка")} и проверить наличие баллона"
;

:  "Нажать на красную медаль, сообщающую, что онлайн-проверка документов отключена"
 "Нажать на медаль {("Красная медаль, сообщающая, что онлайн-проверка документов отключена")} и проверить наличие баллона"
;

: "Установить фокус в баллон красной медали, сообщающую, что онлайн-проверка документов отключена"
 "Красная медаль, сообщающая, что онлайн-проверка документов отключена" byname:control:push pop:reminder:FindEditor pop:control:SetFocus ASSERT
;

: "Установить фокус в баллон зелёной медали МВ"
 "Зелёная медаль МВ" byname:control:push pop:reminder:FindEditor pop:control:SetFocus ASSERT
;

: "Установить фокус в баллон зелёной медали МВ в списке"
 "Зелёная медаль МВ в списке" byname:control:push pop:reminder:FindEditor pop:control:SetFocus ASSERT
;

: "Установить фокус в баллон синей медаль о наличии консультаций"
 "Синяя медаль о наличии консультаций" byname:control:push pop:reminder:FindEditor pop:control:SetFocus ASSERT
;

: "Установить фокус в баллон синей медали документов на контроле в документе"
 контрол::WarnOnControl byname:control:push pop:reminder:FindEditor pop:control:SetFocus ASSERT
;

: "Установить фокус в баллон жёлтой медали с восклицательным знаком"
 "Жёлтая медаль с восклицательным знаком" byname:control:push pop:reminder:FindEditor pop:control:SetFocus ASSERT
; // "Установить фокус в баллон жёлтой медали с восклицательным знаком"

: "Ставим указатель мыши на ссылку в баллоне синей медали документов на контроле в документе"
 "Нажать на медаль {(контрол::WarnOnControl)} и проверить наличие баллона"
 "Установить фокус в баллон синей медали документов на контроле в документе"
 "Ставим указатель мыши на конец текущего параграфа редактора {(focused:control:push)} со смещением {(-100 -10)}"
;

: "Добавить синюю медаль консультаций и сделать" IN aProc

  : Работаем_с_консультацией
   aProc DO
  ; // Работаем_с_консультацией

 : Действия
  "Выполнить {(@ Работаем_с_консультацией )} с импортированой консультацией"
 ;  // Действия

 "Выполнить  {(@ Действия)} со вкладкой консультаций"
 ; // "Добавить синюю медаль консультаций и сделать"

: "Переместить медали по координатам и выполнить" INTEGER IN left_medal INTEGER IN top_medal  IN aProc
 : Работа_с_медалями
  CONST "Синяя медаль с конвертом" 'remUnreadConsultations'
  TRY
   left_medal top_medal true "Синяя медаль с конвертом" byname:control:push pop:reminder:Move
   aProc DO
  FINALLY
    left_medal -1 * =: left_medal
    top_medal -1 * =: top_medal
    left_medal top_medal true "Синяя медаль с конвертом" byname:control:push pop:reminder:Move
  END
 ; // Работа_с_медалями
 "Добавить синюю медаль консультаций и сделать {(@ Работа_с_медалями )}"
; // "Переместить медали по координатам и выполнить" 

: "Переместить медаль по координатам и выполнить" STRING IN aReminder INTEGER IN left_medal INTEGER IN top_medal  IN aProc
  TRY
   left_medal top_medal true aReminder "Найти контрол по имени в стеке" "Переместить медаль"
   aProc DO
  FINALLY
    left_medal -1 * =: left_medal
    top_medal -1 * =: top_medal
    left_medal top_medal true aReminder  "Найти контрол по имени в стеке" "Переместить медаль"
  END
; // "Переместить медаль по координатам и выполнить" 

// $Id: Reminders.script,v 1.38 2013/07/24 07:34:56 a.trofimov Exp $

// $Log: Reminders.script,v $
// Revision 1.38  2013/07/24 07:34:56  a.trofimov
// Добавил тест K472290302.script и эталон для него. Обновил словари и эталон help.script
//
// Revision 1.37  2013/07/10 11:56:02  a.trofimov
// Добавил тест K392697783.script и эталоны для него. Обновил словари и эталон help.script
//
// Revision 1.36  2013/03/18 13:39:11  trofimov
// Обновил словарик и эталон help.script
//
// Revision 1.35  2013/03/07 08:51:29  trofimov
// Дописал тест K265398068.script, сделал правильный эталон. Дополнил словарь и эталон help.script
//
// Revision 1.34  2013/02/26 14:00:00  trofimov
// Добавил тест K390568127.script, эталон для него и консультацию. Обновил словарик и эталон help.script
//
// Revision 1.33  2013/01/21 07:22:07  trofimov
// Добавил тест K390570787.script, эталон к нему, обновил словарь и эталон help.script
//
// Revision 1.32  2012/12/27 08:53:08  trofimov
// Добавил в словари Зеленую медаль МВ в списке и обновил эталон help.script
//
// Revision 1.31  2012/12/12 10:54:20  trofimov
// Добавил импорт медали в тесты K318377771.script, K344136201.script, K380045545.script. А также сами xml, обновил словарь Reminders.script и эталон help.script
//
// Revision 1.30  2012/12/05 12:40:00  trofimov
// Добавил K358365981.script, эталоны к нему, обновил словари и эталон help.script
//
// Revision 1.29  2012/12/01 18:24:39  kostitsin
// следующая пачка слов
//
// Revision 1.28  2012/11/29 11:42:56  trofimov
// Обновил Filters.script, эталон к help.script. Почистил SysUtils.script
//
// Revision 1.27  2012/10/29 11:45:25  selyankin
// добавил K380045545 с эталоном и обновил словарь
//
// Revision 1.26  2012/10/17 07:25:54  selyankin
// обновил "Проверяем, что баллон у медали не видим"
//
// Revision 1.25  2012/10/17 07:23:13  selyankin
// обновил K265410447 и функцию "Нажать на медаль и проверить наличие баллона"
//
// Revision 1.24  2012/10/12 14:00:01  kostitsin
// [$398280432]
//
// Revision 1.23  2012/10/12 10:52:23  kostitsin
// [$398280432]
//
// Revision 1.22  2012/10/08 17:13:46  kostitsin
// Убрал слова:
// -сontrol:Visible,
// -сontrol:Click,
// -сontrol:GetText,
// -сontrol:CanFocus,
// -control:GetHandle
//
// Revision 1.21  2012/10/08 17:06:50  kostitsin
// Убрал слова:
// -сontrol:Visible,
// -сontrol:Click,
// -сontrol:GetText,
// -сontrol:CanFocus,
// -control:GetHandle
//
// Revision 1.20  2012/06/14 13:02:01  kostitsin
// [$358355173]
//
// Revision 1.19  2012/03/26 15:56:16  lulin
// - все наигрались с полуторным интервалом.
//
// Revision 1.18  2012/01/19 17:43:39  lulin
// {RequestLink:328859674}
//
// Revision 1.17  2012/01/10 15:06:51  lulin
// http://mdp.garant.ru/pages/viewpage.action?pageId=317262150&focusedCommentId=326768058#comment-326768058
// - небольшой рефакторинг теста.
//
// Revision 1.16  2011/12/23 15:15:23  lulin
// {RequestLink:318374910}
//
// Revision 1.15  2011/12/19 15:26:04  lulin
// - правим тест за Михаилом.
//
// Revision 1.14  2011/12/19 14:32:08  kostitsin
// http://mdp.garant.ru/pages/viewpage.action?pageId=290262453http://mdp.garant.ru/pages/viewpage.action?pageId=317262150
// http://mdp.garant.ru/pages/viewpage.action?pageId=290262453http://mdp.garant.ru/pages/viewpage.action?pageId=296623811
//
// Revision 1.13  2011/12/09 15:31:11  lulin
// {RequestLink:315261501}
//
// Revision 1.12  2011/12/06 13:23:08  lulin
// {RequestLink:300515360}
//
// Revision 1.11  2011/12/01 17:48:31  lulin
// - делаем "константные" массивы.
//
// Revision 1.10  2011/12/01 14:08:37  lulin
// {RequestLink:304874741}.
//
// Revision 1.9  2011/11/30 17:03:22  lulin
// {RequestLink:304874741}.
//
// Revision 1.8  2011/06/21 13:50:05  lulin
// {RequestLink:265398068}.
//
// Revision 1.7  2011/06/10 09:54:56  lulin
// {RequestLink:269062848}.
//
// Revision 1.6  2011/06/09 14:36:21  lulin
// {RequestLink:269062251}.
//
// Revision 1.5  2011/05/26 14:02:34  lulin
// {RequestLink:266425290}.
//
// Revision 1.4  2011/05/11 18:52:42  lulin
// {RequestLink:236719181}.
// №34.
//
// Revision 1.3  2011/05/11 17:45:26  lulin
// {RequestLink:236719181}.
// №5.
//
// Revision 1.2  2011/05/06 15:49:38  lulin
// - делаем "предложения".
//
// Revision 1.1  2011/05/06 12:14:50  lulin
// {RequestLink:265410566}.
// - выделяем общий код.
//
