{ $Id: CsDefine.inc,v 1.4 2010/05/20 06:30:29 voba Exp $ }

// $Log: CsDefine.inc,v $
// Revision 1.4  2010/05/20 06:30:29  voba
// - не собиралось со старым редактором
//
// Revision 1.3  2006/03/10 09:29:12  voba
// - enh. убрал CsFree etc.
//
// Revision 1.2  2006/02/08 17:24:29  step
// выполнение запросов перенесено из классов-потомков в процедуры объектов
//

{$Define CsDebug}

{$Include evDefine.inc}

{$A-,B-,F+,K-,U-,V-,W-,X+}

{$WriteableConst On}
