USES
 F1ControlsDefinition.script
;

USES
 SysUtils.script
;

: "Открыть фильтры" 
 BOOLEAN VAR l_Found
 true ANYUSERTYPE контрол::FiltersList форма::Filters TryFocusOnForm =: l_Found
 l_Found ! ? filters:Open
 true ANYUSERTYPE контрол::FiltersList форма::Filters TryFocusOnForm
 'Не смогли установить фокус в список фильтров' ASSERTS
;

: "Закрыть фильтры" 
 BOOLEAN VAR l_Found
 true ANYUSERTYPE контрол::FiltersList форма::Filters TryFocusOnForm =: l_Found
 l_Found ? filters:Open
;

: "Открыть фильтры и установить выбранность фильтра в" INTEGER IN aNode BOOLEAN IN aSelected
 : Действия
  "Открыть фильтры"
  aSelected aNode focused:control:push tree:SetSelected
  OnTest
 ;
 "Выполнить {(@ Действия)} и восстановить фокус"
;

: "Открыть фильтры и выбрать" INTEGER IN aNode
 "Открыть фильтры и установить выбранность фильтра {(aNode)} в {(true)}"
;

: "Открыть фильтры и отменить" INTEGER IN aNode
 "Открыть фильтры и установить выбранность фильтра {(aNode)} в {(false)}"
;

: "Открыть фильтры и выбрать второй"
 "Открыть фильтры и выбрать {(1)}"
;

: "Открыть фильтры и выбрать первый"
 "Открыть фильтры и выбрать {(0)}"
;

: "Открыть фильтры и выбрать третий"
 "Открыть фильтры и выбрать {(2)}"
;

: "Открыть фильтры и выбрать четвёртый"
 "Открыть фильтры и выбрать {(3)}"
;

: "Открыть фильтры и выбрать пятый"
 "Открыть фильтры и выбрать {(4)}"
;

: "Проверить, выбран ли фильтр" INTEGER IN aNode
 OBJECT VAR aTree
 "Открыть фильтры" 
 focused:control:push >>> aTree
 aTree ЯВЛЯЕТСЯ class::TnscTreeView 'А все равно нет фокуса в дереве' ASSERTS
 aNode aTree tree:GetSelected .
;

: "Применить фильтр и выполнить" INTEGER IN aNode  IN aProc
 "Открыть фильтры и выбрать {(aNode)}"
 TRY
  aProc DO
 FINALLY
 "Открыть фильтры и отменить {(aNode)}"
 END
; // "Применить фильтр и выполнить" 

: "Проверить, выбран ли фильтр с именем" STRING IN aStr
 "Открыть фильтры" 
 OBJECT VAR aTree
 контрол::FiltersList:push >>> aTree
 INTEGER VAR l_ItemIndex
 0 >>> l_ItemIndex
 "Переместиться в начало дерева"
 aTree "Узнать количество элементов дерева" раз ( 
 ( aTree "Текущая нода дерева" "Текст ноды" ) РАВНО ( aStr ) IF
 "Проверить, выбран ли фильтр {(l_ItemIndex)}"
 EXIT
 ELSE
"Стрелка вниз"
  l_ItemIndex 1 + >>> l_ItemIndex
 ENDIF  )
; // "Проверить, выбран ли фильтр с именем"

// $Id: Filters.script,v 1.26 2013/05/17 11:05:48 a.trofimov Exp $

// $Log: Filters.script,v $
// Revision 1.26  2013/05/17 11:05:48  a.trofimov
// Дописал тест K454041320.script, обновил эталон. Поправил код словаря
//
// Revision 1.25  2013/05/16 13:41:26  a.trofimov
// Дополнил словарь
//
// Revision 1.24  2013/03/11 12:39:59  trofimov
// Добавил тест K387088981.script, эталон к нему, обновил словарик и эталон help.script
//
// Revision 1.23  2012/11/28 13:01:29  trofimov
// Добавил тест K410619503.script, 2 эталона к нему. Создал новый словарик - SysUtils.script, обновил HLTCLike.script, добавил новые слова в  Filters.script
//
// Revision 1.22  2012/11/23 11:45:36  trofimov
// обновил словарь Filters.script (для слова "Проверить, выбран ли фильтр")
//
// Revision 1.21  2012/11/23 11:31:42  trofimov
// обновил словарь Filters.script
//
// Revision 1.20  2012/11/22 13:26:02  trofimov
// Обновил словарик, HLTCLike, добавил тест K400523622 с эталоном
//
// Revision 1.19  2012/11/06 09:08:03  selyankin
// добавил K371647463 с эталоном.
//
// Revision 1.18  2012/11/06 08:18:23  selyankin
// обновил Filters.script
//
// Revision 1.17  2012/11/06 07:56:11  selyankin
// обновил Filters.script
//
// Revision 1.16  2012/11/02 17:43:18  kostitsin
// [$407750239]
//
// Revision 1.15  2012/10/24 09:05:49  lulin
// - рефакторинг.
//
// Revision 1.14  2012/10/12 10:52:23  kostitsin
// [$398280432]
//
// Revision 1.13  2012/10/08 17:13:46  kostitsin
// Убрал слова:
// -сontrol:Visible,
// -сontrol:Click,
// -сontrol:GetText,
// -сontrol:CanFocus,
// -control:GetHandle
//
// Revision 1.12  2012/10/08 12:45:57  selyankin
// обновил функцию "Открыть фильтры и выбрать"
//
// Revision 1.11  2012/10/04 09:38:11  lulin
// - разобрался с дубликатами.
//
// Revision 1.10  2012/10/03 17:25:48  lulin
// - от работы с именами контролов переходим к работе с самими контролами.
//
// Revision 1.9  2012/04/20 06:21:24  lulin
// {RequestLink:356847447}
//
// Revision 1.8  2012/03/19 09:16:06  lulin
// {RequestLink:345636914}
//
// Revision 1.7  2011/12/23 15:15:23  lulin
// {RequestLink:318374910}
//
// Revision 1.6  2011/11/30 13:20:44  lulin
// {RequestLink:307232812}.
// - правим эталоны.
//
// Revision 1.5  2011/06/26 12:57:11  lulin
// {RequestLink:269085062}.
//
// Revision 1.4  2011/05/11 11:01:27  lulin
// {RequestLink:263293374}.
// - готовим рыбу для теста.
//
// Revision 1.3  2011/05/10 14:15:49  lulin
// {RequestLink:236719181}.
// №28.
//
// Revision 1.2  2011/05/06 15:49:38  lulin
// - делаем "предложения".
//
// Revision 1.1  2011/05/06 12:28:18  lulin
// {RequestLink:265410566}.
// - выделяем общий код.
//
