USES
 WordsTranslation.script
 SysUtils.script
;

OBJECT FUNCTION "Найти окно по имени для контрола" STRING IN "Имя окна" OBJECT IN "Контрол"
 "Контрол" =: Result
 VAR "Имя класса главного окна"
 'T' "Имя окна" Cat =: "Имя класса главного окна"

 ПОКА ( Result pop:object:ClassName "НЕ РАВНО" "Имя класса главного окна" )
 BEGIN
  Result pop:control:GetAnotherParentForm =: Result
  Result pop:object:IsNil ! 
   [[ 'Главное окно не найдено: ' "Имя окна" ' для ' "Контрол" pop:component:Name ':' "Контрол" pop:object:ClassName ]] strings:Cat 
    ASSERTS
 END
; // "Найти окно по имени для контрола"

OBJECT FUNCTION "Найти окно по имени" STRING IN "Имя окна"
 "Найти окно по имени {("Имя окна")} для контрола {( focused:control:push )}" =: Result
; // "Найти окно по имени"

OBJECT FUNCTION "Найти главное окно"
 "Найти окно по имени {(форма::MainWindow)}" =: Result
; // "Найти главное окно"

OBJECT FUNCTION "Найти главное окно для контрола" OBJECT IN "Контрол"
 "Найти окно по имени {(форма::MainWindow)} для контрола {("Контрол")}" =: Result
; // "Найти главное окно"

OBJECT FUNCTION "Форма БП"
 ANYUSERTYPE форма::NewBaseSearch vcm:FindForm ASSERT
 >>> Result
; // "Форма БП"

OBJECT FUNCTION "Диалог сохранения в Мои документы"
 'Мои документы (Сохранить как...)' "Найти окно по имени Caption" "Найти контрол по дескриптору в стеке" >>> Result
;

OBJECT FUNCTION "Диалог редактора стилей"
 'Редактор стилей' "Найти окно по имени Caption" "Найти контрол по дескриптору в стеке" >>> Result
;

OBJECT FUNCTION "Измененный диалог редактора стилей"
 'Редактор стилей *' "Найти окно по имени Caption" "Найти контрол по дескриптору в стеке" >>> Result
;

OBJECT FUNCTION "Текстовое окно редактора стилей"
 'f_Editor' "Диалог редактора стилей" "Найти контрол по имени на форме" >>> Result
;

OBJECT FUNCTION "Диалог Условия использования"
 'Условия использования' "Найти окно по имени Caption" "Найти контрол по дескриптору в стеке" >>> Result
;

OBJECT FUNCTION "Диалог Совет дня"
 'Совет дня' "Найти окно по имени Caption" "Найти контрол по дескриптору в стеке" >>> Result
;

OBJECT FUNCTION "Диалог выключения МВ"
 'Выключить Машину времени / Изменить дату' "Найти окно по имени Caption" "Найти контрол по дескриптору в стеке" >>> Result
;