: K392168746

   : Проверяем_статусбар OBJECT IN l_It 
   l_It "Убедиться, что контрол активен" IF
    STRING VAR str1
    STRING VAR str2
    CONST cSeparator '...'
    l_It "Заголовок контрола" >>> str1
    ( str1 "НЕ РАВНО" '' ) IF
      str1 cSeparator string:Split =: str2 =: str1
       ( str1 РАВНО 'Подсчет числа страниц' ) IF
         [[ str1 '... Надпись ЕСТЬ'  ]] strings:Cat >>> str1
         str1 .
       ENDIF
    ENDIF
   ENDIF 
  ; // Проверяем_статусбар

 "Очистить историю"
 "Открываем {(12044185)}"
 THREAD ( 500 SLEEP
 "Для всех видимых элементов статусбара {(контрол::StatusBar:push)} выполнить {(@ Проверяем_статусбар )}" )
 "Предварительный просмотр"
;

K392168746